[build]
builder = "dockerfile"
dockerfilePath = "projects/backend/Dockerfile"
dockerContext = "projects/backend"
watchPatterns = ["projects/backend/**"]

[deploy]
healthcheckPath = "/health"
restartPolicyType = "on_failure"
